ACHWebViewer:
  Servers:
    Public:
      BasePath: "/ach"

  Display:
    Format: "human-readable"
    Masking:
      AccountNumbers: true

  Sources:
    - id: "mergable"
      filesystem:
        paths:
          - "./testdata/"
    # - id: "audittrail"
    #   bucket:
    #     url: "gs://ach-audittrail/"
    #     paths:
    #       - "files"
    #   encryption:
    #     gpg:
    #       keyFile: "/conf/keys/audittrail.priv"
    #       # keyPassword: ""
